variable "aws_region" {}
variable "vpc_id" {}
variable "private_subnet_id1" {}
variable "private_subnet_id2" {}
variable "microservices_load_balancer_arn" {}
variable "ecs_task_execution_role_arn" {}
variable "ecs_task_execution_role_arn" {}
variable "microservices_load_balancer_dns_name" {}
variable "ecs_public_service_sg_id" {}
variable "cloudwatch_event_bus_name" {}
variable "sns_topic_soil_metrics_notifications_arn" {}
variable "sns_topic_weather_notifications_arn" {}
variable "terrafarming_microservices_ecs_cluster_id" {}
variable "terrafarming_microservices_ecs_cluster_name" {}